# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    container_name: bearing_db
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bearing
    ports:
      - "5432:5432"
    volumes:
      - ./table.sql:/docker-entrypoint-initdb.d/table.sql